### ISSUE TITLE
Přidání dalších restaurací

### ISSUE THREAD

**Issue by garcon** [horejsek/lunchtimeandel#1]
http://www.lunchtime.cz/denni-menu-v-okoli/praha-jindricha-plachty/

http://www.lunchtime.cz/blazinec/

**Comment by o5** [comment]
http://prostor.je/#daily-menu

**Comment by horejsek** [comment]
https://github.com/horejsek/lunchtimeandel/commit/e782e7260be1130fa4c53a006b56c824fff311b7

**Comment by o5** [comment]
:+1:
