### ISSUE TITLE
Bernard Pub a Formanka vypadla z mapy

### ISSUE THREAD

**Issue by martinsuchan** [horejsek/lunchtimeandel#10]

**Comment by horejsek** [comment]
To není bug, ale feature. Tam pořád všichni chodí a už mne to unavuje. :-))

BernardPub už nemá na stránkách menu a u Formanky mi to v logu píše něco se špatnými argumenty. Nějak změnily strukturu stránky zřejmě, ale od oka zatím nevidím kde. Každopádně by se mělo minimálně zobrazit, že denní menu není k dispozici. Momentálně mi blbne vývojový server, tak se na to podívám. Snad v dohledné době.

**Comment by horejsek** [comment]
Tak BernadPub má menu, jen v den kdy jsem koukal tam nebylo. A je to úplně jiné. Každopádně platí, že potrvá, než se k tomu dostanu. Teď to není moje priorita. Pull requesty vítány. :-)

**Comment by martinsuchan** [comment]
Nebyl by už čas na opravu? :) Rád bych lunchtimeandel.cz opět začal využívat.
Dík

**Comment by horejsek** [comment]
@pavelsterba připravuje úplně novou verzi. Jak to vypadá, Pavle? :-)

**Comment by vanekjar** [comment]
Formanku jsem fixnul v pull requstu #17. Bernard je trochu pain na parsování.

**Comment by horejsek** [comment]
Mockrát děkuji. Je to venku a běží. :-)

**Comment by martinsuchan** [comment]
U Bernarda by se aspon hodil odkaz na stranky restaurace, jako je to u jinych podniku, pokud je parsovani slozite.

**Comment by jan-rohan** [comment]
Bernard parser má a dokonce parsuje správně (ověřeno lokálně). Proč se na produkční webovce Bernard neukazuje když lokálně jo? Není tam nějaká chyba třeba v DB? Protože čistě v kódu se jeví vše ok.

**Comment by horejsek** [comment]
To bude cenzura. Kdo by chtěl chodit do Bernarda? :-)) Vtípkuji, podívám se na to. Možná může být problém, že z mého serveru se na ten web nedovolá.
